" activate pathogen plugin manager
execute pathogen#infect()

syntax on
filetype plugin indent on

" Indentation
set autoindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Colors
colorscheme molokai
set background=dark

" activate mouse in all modes
set mouse=a

" show some invisible characters
set list

" map semicolon to colon
" That way you dont need to hold Shift to enter cmdline mode
map ; :

" map `Y` to yank to the end of the line
" You can still yank the entire line with `yy`
nmap Y y$

" recognize .md files as markdown
au BufRead,BufNewFile *.md set filetype=markdown

" if our terminal supports escape sequences
if &term == "screen-256color"
  " set the insert mode cursor to a blinking vertical bar
  let &t_SI = "\<Esc>[5 q"
  " in other modes, set the cursor to a blinking block
  let &t_EI = "\<Esc>[0 q"

  " 1 or 0 -> blinking block
  " 2 -> solid block
  " 3 -> blinking underscore
  " 4 -> solid underscore
  " 5 -> blinking vertical bar
  " 6 -> solid vertical bar
endif

" enable rubocop
let g:syntastic_ruby_checkers = ['mri', 'rubocop']
