" activate pathogen plugin manager
execute pathogen#infect()

syntax on
filetype plugin indent on

" Indentation
set autoindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Colors
colorscheme molokai
set background=dark

" activate mouse in all modes
set mouse=a

" show some invisible characters
set list

" map semicolon to colon
" That way you dont need to hold Shift to enter cmdline mode
map ; :

" map `Y` to yank to the end of the line
" You can still yank the entire line with `yy`
nmap Y y$

" recognize .md files as markdown
au BufRead,BufNewFile *.md set filetype=markdown

" Support different cursor in insert mode.
if &term == "screen-256color"
  let &t_SI = "\<Esc>[3 q"
  let &t_EI = "\<Esc>[0 q"
endif

" enable rubocop
let g:syntastic_ruby_checkers = ['mri', 'rubocop']
