---
  - name: install or update pyenv
    git: >
      repo=git://github.com/yyuu/pyenv.git
      dest={{ home }}/.pyenv

  - name: make dotfiles directory
    file: path={{ dotfiles }}/python state=directory recurse=yes

  - name: copy pyenv.esh
    copy: src=pyenv.sh dest={{ dotfiles }}/python/pyenv.sh
    notify: build .profile

  - name: install global python version
    when: global is defined
    command: >
      "{{ home }}/.pyenv/bin/pyenv install {{ global }}"
      creates={{ home }}/.pyenv/versions/{{ global }}

  - name: set global python version
    when: global is defined
    command: "{{ home }}/.pyenv/bin/pyenv global {{ global }}"
