---
  - name: check on build dependencies
    apt: pkg={{ item }} state=present
    sudo: yes
    with_items:
      - libcurl4-gnutls-dev
      - libexpat1-dev
      - gettext
      - libz-dev
      - libssl-dev
      - libpcre3-dev

  - name: check if we can git
    command: git --version
    register: cangit
    ignore_errors: yes

  - name: add the package for just a sec
    apt: pkg=git state=present
    sudo: yes
    when: cangit|failed

  - name: download source
    git: repo=git://git.kernel.org/pub/scm/git/git.git dest={{ build }}/git
    register: gitsource

  - include: build.yml
    when: gitsource | changed

  - name: template gitconfig
    template: src=gitconfig dest={{ home }}/.gitconfig

  - name: copy dotfiles
    copy: src={{ item }} dest={{ home }}/.{{ item }}
    with_items:
      - git_template

  - name: make dotfiles directory
    file: path={{ dotfiles }}/git state=directory recurse=yes

  - name: copy git.sh
    copy: src=git.sh dest={{ dotfiles }}/git/git.sh
    notify: build .profile

  - name: copy basic linux gitignore
    get_url: >
      dest={{ dotfiles }}/git/
      url=https://raw.githubusercontent.com/github/gitignore/master/Global/Linux.gitignore

  - name: copy ssh config
    copy: src=ssh_config dest={{ home }}/.ssh/config
