---
- name: find python 2.7 config dir
  command: /usr/bin/python2.7-config --configdir
  register: python_2_7_config

- name: find python 3 config dir
  command: /usr/bin/python3-config --configdir
  register: python_3_config

- name: configure
  command: >
    ./configure
    --enable-cscope
    --enable-gui=no
    --enable-multibyte
    --enable-pythoninterp=dynamic
    --enable-python3interp=dynamic
    --with-python-config-dir={{ python_2_7_config.stdout }}
    --with-python3-config-dir={{ python_3_config.stdout }}
    --enable-rubyinterp
    --with-features=huge
    --with-tlib=ncurses
    --without-x
    chdir={{ build }}/vim

- name: make
  command: make chdir={{ build }}/vim

- name: install
  command: make install chdir={{ build }}/vim
  sudo: yes
