---
- name: install exuberant ctags
  apt: pkg=exuberant-ctags state=present
  sudo: yes

- name: required packages
  apt: pkg={{ item }} state=present
  sudo: yes
  with_items:
    - mercurial # scm we pull with
    - libncurses5-dev #  --with-tlib=ncurses
    - ruby-dev # --enable-rubyinterp

- name: clone vim
  hg: dest={{ build }}/vim repo=https://vim.googlecode.com/hg/ force=no
  register: vim_repo

- include: build.yml
  when: vim_repo|changed

- name: create .vim subdirectories
  file: path={{ home }}/.vim/{{ item }} state=directory
  with_items:
    - autoload
    - bundle
    - colors

- name: install pathogen
  get_url: dest={{ home }}/.vim/autoload/ url=https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim

- name: install vim plugins
  git: repo=git://github.com/{{ item }}.git dest={{ home }}/.vim/bundle/{{ item | basename }}
  with_items: vim_plugins
  ignore_errors: yes

- name: install molokai
  get_url: dest={{ home }}/.vim/colors/ url=https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim

- name: install .vimrc
  copy: dest={{ home }}/.vimrc src=vimrc
